import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Raleway } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { SiteHeader } from "@/components/site-header";
import { AppSidebar } from "@/components/app-sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { getAllEpics } from "@/lib/supabase/test-cases";

const montserratHeading = Montserrat({subsets:['latin'],variable:'--font-montserrat'});

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({ children }: LayoutProps<"/">) {
	const epics = await getAllEpics();
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, montserratHeading.variable, raleway.variable)}
    >
      <body className="h-full flex flex-col overflow-hidden">
        <SidebarProvider
        style={
          {
            "--sidebar-width": "calc(var(--spacing) * 72)",
            "--header-height": "calc(var(--spacing) * 12)",
          } as React.CSSProperties
        }>
          <AppSidebar variant="inset" epics={epics}/>
            <SidebarInset>
              {/* <SiteHeader/> */}
			  <TooltipProvider>
				<div className="flex min-h-0 flex-1 flex-col gap-4 overflow-y-hidden">
					{children}
				</div>
			  </TooltipProvider>
            </SidebarInset>
        </SidebarProvider>
        
      </body>
    </html>
  );
}
