import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Raleway } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { SiteHeader } from "@/components/site-header";
import { AppSidebar } from "@/components/app-sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { getTestingSuites } from "@/lib/supabase/Init";
import { getCurrentUser } from "@/lib/supabase/auth";
import { CurrentUserProvider } from "@/components/current-user-provider";


const montserratHeading = Montserrat({ subsets: ['latin'], variable: '--font-heading' });


const raleway = Raleway({
	subsets: ["latin"],
	variable: "--font-raleway",
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};



export default async function RootLayout({ children }: LayoutProps<"/">) {
	const user = await getCurrentUser();
	const htmlClassName = cn("h-full", "antialiased", geistSans.variable, geistMono.variable, montserratHeading.variable, raleway.variable);

	// Logged out: only /login is reachable (see proxy.ts), and it renders without the app shell.
	if (!user) {
		return (
			<html lang="en" className={htmlClassName}>
				<body className="h-full flex flex-col overflow-hidden">
					<TooltipProvider>{children}</TooltipProvider>
				</body>
			</html>
		);
	}

	const testSuites = await getTestingSuites();
	return (
		<html
			lang="en"
			className={htmlClassName}
		>
			<body className="h-full flex flex-col overflow-hidden">
				<CurrentUserProvider user={user}>
				<TooltipProvider>
					<SidebarProvider
						style={
							{
								"--sidebar-width": "calc(var(--spacing) * 72)",
								"--header-height": "calc(var(--spacing) * 12)",
							} as React.CSSProperties
						}>
						<AppSidebar testingSuites={testSuites} user={user} />
						<SidebarInset>
							<div className="flex min-h-0 flex-1 flex-col gap-4 overflow-y-hidden">
								<SiteHeader testingSuites={testSuites} />
								{children}
							</div>
						</SidebarInset>
					</SidebarProvider>
				</TooltipProvider>
				</CurrentUserProvider>
			</body>
		</html>
	);
}
